# Copyright © 2024 Giovanni Squillero <squillero@polito.it>
# https://github.com/squillero/computer-sciences
# Free for personal or classroom use; see 'LICENSE.md' for details.

[tool.black]
    exclude     = "(^\\.|^__pycache__)"
    include     = "\\.py$"
    line-length = 120

[tool.poetry]
    authors      = ["Giovanni Squillero <giovanni.squillero@polito.it>"]
    description  = "Clean environment for Computater Sciences"
    license      = "proprietary"
    package-mode = false

    [tool.poetry.dependencies]
        python = "^3.10"
        black  = "^24.4.2"

    [tool.poetry.dev-dependencies]

[build-system]
    requires      = ["poetry-core"]
    build-backend = "poetry.core.masonry.api"
